import { Box, Grid } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primaryBackground">
        <Box sx={{ height: "100vh" }}>{children}</Box>
      </body>
    </html>
  );
}
