import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import { darkTheme } from "@/theme/muitheme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import StoreProvider from "./StoreProvider";
import { Box } from "@mui/system";
import { Toaster } from "react-hot-toast";
import dynamic from "next/dynamic";
const MiniDrawer = dynamic(() => import("../components/Darwer"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={darkTheme}>
          <body>
            <StoreProvider>
              <Box
                sx={{ height: "100vh", backgroundColor: "background.default" }}
              >
                <div>
                  <Toaster position="top-center" />
                </div>
                <MiniDrawer>{children}</MiniDrawer>
              </Box>
            </StoreProvider>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
